import "./globals.css";

export const metadata = {
  title: "Ken Zhang",
  description: "Generated by create next app",
  icons: {
    icon: "/svg/zhang_logo_white.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
